// src/data/fishSpecies.js
const germanFishSpecies = [
  'Aal',
  'Aland',
  'Äsche',
  'Bachforelle',
  'Bachsaibling',
  'Barbe',
  'Barsch',
  'Bitterling',
  'Brassen',
  'Döbel',
  'Elritze',
  'Flunder',
  'Gründling',
  'Güster',
  'Hecht',
  'Karausche',
  'Karpfen',
  'Kaulbarsch',
  'Lachs',
  'Laube (Ukelei)',
  'Meerforelle',
  'Nase',
  'Regenbogenforelle',
  'Rotauge',
  'Rotfeder',
  'Rutte (Quappe)',
  'Schleie',
  'Schmerle',
  'Seeforelle',
  'Seesaibling',
  'Stint',
  'Wels',
  'Weißfisch',
  'Zander',
  'Zope',
];

export default germanFishSpecies;
