@baseUrl =  http://localhost:3000/api

GET {{baseUrl}}/catches

###

POST {{baseUrl}}/catches
Content-Type: application/json

{
    "species": "Barsch",
    "_id": "0.4039550408208712"
}

### DELETE

DELETE {{baseUrl}}/catches
Content-Type: application/json

{
    "_id": "0.4039550408208712"
}