@baseUrl =  http://localhost:3000/api

### Login with name and password

POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "Caspar_Velsen",
    "password": "crvelsen23"
}

### Get profile via acces token

GET {{baseUrl}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjU1OWI5YTFhMWI5NzZkMzYyZmY0NWYiLCJpYXQiOjE2NDk3NzgwOTR9.lCG2hDPfzdv3gX1v7h2EsLuRSvW1RB6Qh0xYVi3f28c